/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyPackage_NativeClass */

#ifndef _Included_MyPackage_NativeClass
#define _Included_MyPackage_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyPackage_NativeClass
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyPackage_NativeClass_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     MyPackage_NativeClass
 * Method:    UseEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyPackage_NativeClass_UseEnv
  (JNIEnv *, jobject);

/*
 * Class:     MyPackage_NativeClass
 * Method:    Square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MyPackage_NativeClass_Square
  (JNIEnv *, jobject, jint);

/*
 * Class:     MyPackage_NativeClass
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyPackage_NativeClass_getLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MyPackage_NativeClass
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_MyPackage_NativeClass_sumArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     MyPackage_NativeClass
 * Method:    accessObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyPackage_NativeClass_accessObject
  (JNIEnv *, jobject);

/*
 * Class:     MyPackage_NativeClass
 * Method:    makeCallback
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MyPackage_NativeClass_makeCallback
  (JNIEnv *, jobject, jint);

/*
 * Class:     MyPackage_NativeClass
 * Method:    checkForException
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MyPackage_NativeClass_checkForException
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
