package examples.equality.ex3;

import java.util.HashSet;

public class EqualityAndHashes {

	public static void main(String[] args) {
		Vector3 v1 = new Vector3(5, 7);
		Vector3 v2 = new Vector3(5, 7);
		Vector3 v3 = new Vector3(2, 8);
		HashSet<Vector3> collection = new HashSet<Vector3>();
		// hashCode called when object added to collection
		
		collection.add(v1);
		collection.add(v3);
		
		// this should print true because v1 is equal to v2
		System.out.println(v1.equals(v2));
		
		// this should print true because v1 is equal to v2
		System.out.println(collection.contains(v2));
	}

}
// the equals and hashcode methods were generated by Eclipse

class Vector3 {

	@Override
	public int hashCode() {
		System.out.println("hashCode called");
		final int prime = 31;
		int result = 1;
		result = prime * result + x;
		result = prime * result + y;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		System.out.println("equals called");
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vector3 other = (Vector3) obj;
		if (x != other.x)
			return false;
		if (y != other.y)
			return false;
		return true;
	}

	private final int x;
    private final int y;

    public Vector3(int x, int y) {
        this.x = x;
        this.y = y;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }
}
